# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainenv < Formula
  desc ""
  homepage ""
  version "1.0.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dvcrn/chainenv/releases/download/1.0.0/chainenv_Darwin_x86_64.tar.gz"
    sha256 "07e9a3dde3593df1d7c18f31fce4250fa28ba6dba760608b5e7a4368a549d177"

    def install
      bin.install "chainenv"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dvcrn/chainenv/releases/download/1.0.0/chainenv_Darwin_arm64.tar.gz"
    sha256 "c143e39fc9165840a2b0ce7a6226112bc4a272470b3244eee56bb14532f06353"

    def install
      bin.install "chainenv"
    end
  end
end
