# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainenv < Formula
  desc ""
  homepage ""
  version "1.0.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dvcrn/chainenv/releases/download/1.0.0/chainenv_Darwin_x86_64.tar.gz"
    sha256 "705f54c9fd1a8c0b6920d7fd92686f1b8a481209800add0ac2fdd20dd7a8ed18"

    def install
      bin.install "chainenv"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dvcrn/chainenv/releases/download/1.0.0/chainenv_Darwin_arm64.tar.gz"
    sha256 "9e31cb5ab168ce8aa0645432e87f5cff2060c216bf74f544db01107d106f87c9"

    def install
      bin.install "chainenv"
    end
  end
end
