# This file was generated by GoReleaser. DO NOT EDIT.
cask "wework-cli" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "99cfd2286cb229a7bd3d21debc255d3abfe7331f04ff44abc6d211db18c0e413"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d4d402b42afc04457eacce6b87984644ab749db3b1dd66e56f5341e7f09bbd3"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1dd07a177909d026e1e2e8421109a08d26d1bb002e444d2d44b89ae8624b223f"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de2d29c878bbb861158602b2b09338b940d0c85d9a03d5ebabf6ce65477d427f"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wework-cli"
  desc "CLI tool for booking WeWork spaces"
  homepage "https://github.com/dvcrn/wework-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wework"

  # No zap stanza required
end
