# This file was generated by GoReleaser. DO NOT EDIT.
cask "wework-cli" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "fc76cab41b5dcfcc581d49a2c44d22ba6cb0a428159bbcc813dfa1de58d86b43"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "63d6f8c573cde3541c66131252f4e4f2d7abf5590edc2d26aad5bd4e10fe2dff"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0e83fa799e39680972a9267383c3f94f9142aee5fc964b5ad2d90b5303f079a"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0df3a5c7c6acf5ef3c9d96be0d0c878b0d724da1b07a2e59bc8a0aa958b18f3"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wework-cli"
  desc "CLI tool for booking WeWork spaces"
  homepage "https://github.com/dvcrn/wework-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wework"

  # No zap stanza required

end
