# This file was generated by GoReleaser. DO NOT EDIT.
cask "wework-cli" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "e3f0b3e740cac04023afb3f9cbe79caa3504682a317c1f41a163b6dc42946563"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2153c251f1b9b55a7663bcdcffa0576614801ec152cbfc2ce124a8741bedf772"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a331cef1a143d0fdca2dc542a2749af670c1c4ba59d4cd73b2ef3c4aa5db2e1a"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10811a26a6438968aebed200ebb08f9faf388777f98c1e1bee848e7eb428ce40"
      url "https://github.com/dvcrn/wework-cli/releases/download/#{version}/wework_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wework-cli"
  desc "CLI tool for booking WeWork spaces"
  homepage "https://github.com/dvcrn/wework-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wework"

  # No zap stanza required

end
